title                                     : Dashcam for your Bike app                 # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1577996345                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.dashcambike.dashcamapp
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : ./assets/icon.png                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Dashcam for your Bike                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Turn your smartphone into a dashcam. Capture cars blocking bike lanes and other daily hazards. Available on iOS, and now ready for beta testing on Android.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Dashcam for your Bike, Inc
your_link                                 : https://www.linkedin.com/company/79463047/
your_city                                 : Pittsburgh, PA
email_address                             : hello@dashcam.bike
facebook_username                         : Dashcam-for-your-Bike-App-112118611370858
instagram_username                        : DashcamBike
twitter_username                          : DashcamBike
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :
  - title                                 : Super low-power
    description                           : A 20-minute commute uses around 5% of your battery
    fontawesome_icon_name                 : battery-full

  - title                                 : Gesture-based controls
    description                           : Start and stop recording without looking at your phone
    fontawesome_icon_name                 : map-marked

  - title                                 : Ride with Music
    description                           : Compatible with Spotify, Podcasts, and more
    fontawesome_icon_name                 : music
    
  - title                                 : Records GPS tracks
    description                           : So you can easily find events worth sharing
    fontawesome_icon_name                 : map-marker-alt

  - title                                 : Fast playback
    description                           : Playback and export videos at up to 32x speed
    fontawesome_icon_name                 : fast-forward

  - title                                 : 3D Compilation Videos
    description                           : Share to social media, or save videos to your phone
    fontawesome_icon_name                 : share-alt
  
  - title                                 : Smart Storage
    description                           : Automatically deletes oldest videos to save storage space
    fontawesome_icon_name                 : save

  - title                                 : Fast 311 Reports
    description                           : Share dangerous conditions with your city with a couple taps
    fontawesome_icon_name                 : flag

  - title                                 : Video Editing
    description                           : Simple video trimming features to just share the relevant moment
    fontawesome_icon_name                 : video


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : ./assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#161b1d"
cover_overlay_transparency                : 0.9

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#cfcfcf"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#e9e9e9"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
google_analytics: G-FYFE0DB37S

url: "https://dashcam.bike" # the base hostname & protocol for your site for jekyll-sitemap
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
