title                                     : Dashcam for your Bike app                 # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1577996345                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.dashcambike.dashcamapp
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : ./assets/icon.png                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Dashcam for your Bike                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Turn your smartphone into a dashcam.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Dashcam for your Bike, Inc
your_link                                 : https://www.linkedin.com/company/79463047/
email_address                             : hello@dashcam.bike
facebook_username                         : Dashcam-for-your-Bike-App-112118611370858
instagram_username                        : DashcamBike
twitter_username                          : DashcamBike
github_username                           : 
youtube_username                          :

# SEO (https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md)
twitter:
    username: DashcamBike
    card: summary
logo: /assets/oglogo.png
tagline: Turn your smartphone into a dashcam
description: Turn your smartphone into a dashcam. Capture cars blocking bike lanes and other daily hazards. Available on iOS, and now ready for beta testing on Android.


# FAQs
faqs                                      :
  - title                                 : What's the battery life like?
    description                           : A 20-minute commute uses around 5% of your battery
    fontawesome_icon_name                 : battery-full

  - title                                 : I can't see my screen.
    description                           : Everything is controllable via gestures so you can start and stop recording without looking at your phone.
    fontawesome_icon_name                 : map-marked

  - title                                 : Can I listen to music?
    description                           : Yes, you can listen to music and podcasts. After launching the app, just tap Play to continue listening.
    fontawesome_icon_name                 : music
    
  - title                                 : What is Smart Storage?
    description                           : When you reach your storage limit, we overwrite the oldest footage. Your storage limit is customizable.
    fontawesome_icon_name                 : save

  - title                                 : How do I report hazards?
    description                           : Share dangerous conditions with your city with a couple taps. See <a href="/311">instructions</a>.
    fontawesome_icon_name                 : flag

  - title                                 : How do I make flyover vids?
    description                           : Just hit Share, then Select Clips. Choose the clips you want to share. If you select multiple clips, we'll create a flyover transition between them.
    fontawesome_icon_name                 : video


# Theme Settings
main_text_color                           : "#e9e5eb"
highlighted_text_color                    : "#c7a8eb"
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : ./assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#161b1d"
cover_overlay_transparency                : 0.9

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#cfcfcf"

feature_icons_foreground_color            : "#6930b2"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#e9e9e9"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
google_analytics: G-FYFE0DB37S

url: "https://dashcam.bike" # the base hostname & protocol for your site for jekyll-sitemap
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
